; test.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 55.0
.source test.java
.class public test
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 1
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public main([Ljava/lang/String;)V
  .limit stack 4
  .limit locals 3
  .line 13
  0: iconst_3
  1: newarray int
  3: dup
  4: iconst_0
  5: iconst_1
  6: iastore
  7: dup
  8: iconst_1
  9: iconst_1
  10: iastore
  11: dup
  12: iconst_2
  13: iconst_2
  14: iastore
  15: astore_2
  .line 14
  16: aload_2
  17: iconst_0
  18: iconst_3
  19: iastore
  .line 15
  20: return
.end method

.method public foo(I)V
  .limit stack 2
  .limit locals 4
  .line 17
  0: iconst_5
  1: istore_2
  .line 18
  2: iload_2
  3: iconst_2
  4: isub
  5: istore_3
  .line 19
  6: return
.end method

