; test.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 61.0
.source test.java
.class public test
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 1
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public main([Ljava/lang/String;)V
  .limit stack 4
  .limit locals 4
  .line 12
  0: iconst_3
  1: newarray int
  3: dup
  4: iconst_0
  5: iconst_1
  6: iastore
  7: dup
  8: iconst_1
  9: iconst_1
  10: iastore
  11: dup
  12: iconst_2
  13: iconst_2
  14: iastore
  15: astore_2
  .line 13
  16: aload_2
  17: iconst_0
  18: iconst_3
  19: iastore
  .line 14
  20: bipush 10
  22: newarray int
  24: astore_3
  .line 15
  25: aload_3
  26: iconst_0
  27: aload_3
  28: iconst_1
  29: iaload
  30: iconst_1
  31: iadd
  32: iastore
  .line 18
  33: return
.end method

